### ISSUE TITLE
Unused memtest code could be replaced by e820

### ISSUE THREAD

**Issue by wjn740** [crazyss/hypervisor_last#21]
https://github.com/crazyss/hypervisor_last/blob/8a6b11f9a9dc9ba7d0cdb1496abf1847c8744216/hypervisor/start.c#L133
This code will cause the system crash due to paging fault, (we don't have page fault handler right now).
So, originally, I use this code to compute how many memory do we have. for now we should use e820.
@coolgw would you please take a look.

remove unused code, read the real data from e820 table, and display them on the screen.

**Comment by coolgw** [comment]
@wjin740
Some investigation result:
The memory map (which get by int15) show following address area is reserved
base: 0x1fe0000   length: 0x20000
but, if you change code to memtotal=memtest(0x400000, 0x1999999) it still show no crash, so we need firstly find out why this happen.

**Comment by wjn740** [comment]
The crash caused by accessing unmaping memory. Not the memory is reserved.

**Comment by coolgw** [comment]
> The crash caused by accessing unmaping memory. Not the memory is reserved.

what i mean is e820 table is not correct, we can not rely on the result of e820 table.

**Comment by wjn740** [comment]
> > The crash caused by accessing unmaping memory. Not the memory is reserved.
> 
> what i mean is e820 table is not correct, we can not rely on the result of e820 table.

why do you think about it's wrong? because writing a "reserved" memory didn't happen crash ?

**Comment by coolgw** [comment]
1) Max page size should also calculated by e820 result
2) Test all valid memory area
